import { scryptSync } from "node:crypto";
import { describe, expect, it, vi } from "vitest";
import { DispatchPersistenceError } from "@/domain/dispatch-assignment-gateway";
import type { DispatchAssignmentGateway, DurableAssignment } from "@/domain/dispatch-assignment-gateway";
import { confirmDispatchAssignment, overrideDispatchAssignment } from "@/server/dispatch-commands";
import { createSessionToken, type OwnerConfig } from "@/server/owner-auth";

const owner: OwnerConfig = { id: "owner", username: "ngoc", displayName: "Ngoc", passwordScrypt: `salt:${scryptSync("pw", "salt", 64).toString("hex")}`, sessionSecret: "safe-secret" };
const assignment: DurableAssignment = { id: "00000000-0000-4000-8000-000000000100", orderId: "00000000-0000-4000-8000-000000000001", employeeId: "00000000-0000-4000-8000-000000000002", startsAt: new Date("2030-01-01T08:00:00Z"), endsAt: new Date("2030-01-01T09:00:00Z"), status: "SCHEDULED", isOverride: false, overrideReason: null };
const input = { orderId: assignment.orderId, employeeId: assignment.employeeId, startsAt: "2030-01-01T08:00:00.000Z", endsAt: "2030-01-01T09:00:00.000Z", expectedOrderVersion: "2030-01-01T00:00:00.000000Z" };
function dependencies(cause: "ELIGIBLE" | "EMPLOYEE_INACTIVE" | "EMPLOYEE_MISSING_REQUIRED_SKILL" | "EMPLOYEE_OFF" | "ORDER_NOT_ASSIGNABLE" = "ELIGIBLE") {
  const gateway: DispatchAssignmentGateway = { confirmAssignment: vi.fn(), overrideAssignment: vi.fn(), confirmAssignmentWithVersion: vi.fn().mockResolvedValue({ assignment, orderVersion: "next" }), overrideAssignmentWithVersion: vi.fn().mockResolvedValue({ assignment: { ...assignment, isOverride: true, overrideReason: "Reason" }, orderVersion: "next" }), replaceOrderAssignment: vi.fn(), cancelOrder: vi.fn(), loadOrderAssignments: vi.fn(), listToursWithAssignedEmployees: vi.fn(), markEmployeeOff: vi.fn(), unmarkEmployeeOff: vi.fn() };
  return { owner, gateway, eligibility: { evaluateEligibility: vi.fn().mockResolvedValue(cause) } };
}
describe("durable dispatch commands", () => {
  it("rejects an unauthenticated request before eligibility or gateway work", async () => { const d = dependencies(); await expect(confirmDispatchAssignment(input, undefined, d)).resolves.toMatchObject({ ok: false, error: "UNAUTHENTICATED" }); expect(d.eligibility.evaluateEligibility).not.toHaveBeenCalled(); expect(d.gateway.confirmAssignmentWithVersion).not.toHaveBeenCalled(); });
  it("rejects invalid input without invoking durable eligibility", async () => { const d = dependencies(); await expect(confirmDispatchAssignment({ ...input, orderId: "" }, createSessionToken(owner), d)).resolves.toMatchObject({ ok: false, error: "INVALID_INPUT" }); expect(d.eligibility.evaluateEligibility).not.toHaveBeenCalled(); });
  it("maps durable hard eligibility causes without accepting client authority", async () => { const d = dependencies("EMPLOYEE_MISSING_REQUIRED_SKILL"); await expect(confirmDispatchAssignment(input, createSessionToken(owner), d)).resolves.toMatchObject({ ok: false, error: "EMPLOYEE_MISSING_REQUIRED_SKILL" }); expect(d.gateway.confirmAssignmentWithVersion).not.toHaveBeenCalled(); });
  it("blocks OFF employees through both normal and override command paths", async () => { const d = dependencies("EMPLOYEE_OFF"); await expect(confirmDispatchAssignment(input, createSessionToken(owner), d)).resolves.toMatchObject({ ok: false, error: "EMPLOYEE_OFF" }); await expect(overrideDispatchAssignment({ ...input, reason: "Cannot bypass OFF" }, createSessionToken(owner), d)).resolves.toMatchObject({ ok: false, error: "EMPLOYEE_OFF" }); expect(d.gateway.confirmAssignmentWithVersion).not.toHaveBeenCalled(); expect(d.gateway.overrideAssignmentWithVersion).not.toHaveBeenCalled(); });
  it("confirms through the versioned boundary and maps stale safely", async () => { const d = dependencies(); await expect(confirmDispatchAssignment(input, createSessionToken(owner), d)).resolves.toMatchObject({ ok: true, result: { orderVersion: "next" } }); expect(d.gateway.confirmAssignmentWithVersion).toHaveBeenCalledWith(expect.objectContaining({ orderId: input.orderId, employeeId: input.employeeId, expectedOrderVersion: input.expectedOrderVersion, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt) })); d.gateway.confirmAssignmentWithVersion = vi.fn().mockRejectedValue(new DispatchPersistenceError("STALE_VERSION")); await expect(confirmDispatchAssignment(input, createSessionToken(owner), d)).resolves.toMatchObject({ ok: false, error: "STALE_VERSION", message: "Dữ liệu tour đã thay đổi. Hãy tải lại trước khi xác nhận." }); });
  it("requires a nonblank override reason and otherwise uses only the override boundary", async () => { const d = dependencies(); await expect(overrideDispatchAssignment({ ...input, reason: "  " }, createSessionToken(owner), d)).resolves.toMatchObject({ ok: false, error: "INVALID_INPUT" }); await expect(overrideDispatchAssignment({ ...input, reason: "  Reason  " }, createSessionToken(owner), d)).resolves.toMatchObject({ ok: true }); expect(d.gateway.overrideAssignmentWithVersion).toHaveBeenCalledWith(expect.objectContaining({ reason: "Reason" })); expect(d.gateway.confirmAssignmentWithVersion).not.toHaveBeenCalled(); });
  it("revalidates UNKNOWN skill differently for normal confirmation and explicit override", async () => {
    const d = dependencies("EMPLOYEE_MISSING_REQUIRED_SKILL");
    d.eligibility.evaluateEligibility = vi.fn().mockImplementation((_orderId, _employeeId, options) => Promise.resolve(options?.allowUnknownSkill ? "ELIGIBLE" : "EMPLOYEE_MISSING_REQUIRED_SKILL"));
    await expect(confirmDispatchAssignment(input, createSessionToken(owner), d)).resolves.toMatchObject({ ok: false, error: "EMPLOYEE_MISSING_REQUIRED_SKILL" });
    await expect(overrideDispatchAssignment({ ...input, reason: "Accept incomplete skill data" }, createSessionToken(owner), d)).resolves.toMatchObject({ ok: true });
    expect(d.eligibility.evaluateEligibility).toHaveBeenNthCalledWith(1, input.orderId, input.employeeId);
    expect(d.eligibility.evaluateEligibility).toHaveBeenNthCalledWith(2, input.orderId, input.employeeId, { allowUnknownSkill: true });
  });
});
