import { beforeEach, describe, expect, it, vi } from "vitest";
import { scryptSync } from "node:crypto";

const mocks = vi.hoisted(() => ({ confirm: vi.fn(), override: vi.fn(), markOff: vi.fn(), unmarkOff: vi.fn(), revalidate: vi.fn(), redirect: vi.fn(), cookieGet: vi.fn(), cookieSet: vi.fn(), composition: vi.fn(), headers: vi.fn() }));
vi.mock("next/headers", () => ({ cookies: vi.fn(async () => ({ get: mocks.cookieGet, set: mocks.cookieSet })), headers: mocks.headers }));
vi.mock("next/navigation", () => ({ redirect: mocks.redirect }));
vi.mock("next/cache", () => ({ revalidatePath: mocks.revalidate }));
vi.mock("@/server/dispatch-composition", () => ({ createDispatchServerDependencies: mocks.composition }));
vi.mock("@/server/dispatch-commands", () => ({ confirmDispatchAssignment: mocks.confirm, overrideDispatchAssignment: mocks.override, markEmployeeOff: mocks.markOff, unmarkEmployeeOff: mocks.unmarkOff }));
import { confirmOwnerDispatch, login, logout, markOwnerEmployeeOff, overrideOwnerDispatch, unmarkOwnerEmployeeOff } from "@/app/actions";

const initial = { ok: false, message: "" };
function form(overrides: Record<string, string> = {}) { const data = new FormData(); const values = { orderId: "00000000-0000-4000-8000-000000000001", employeeId: "00000000-0000-4000-8000-000000000002", startsAt: "2030-01-01T08:00:00.000Z", endsAt: "2030-01-01T09:00:00.000Z", expectedOrderVersion: "2030-01-01T00:00:00.123456Z", ...overrides }; for (const [key, value] of Object.entries(values)) data.set(key, value); return data; }
describe("public dispatch Server Actions", () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.redirect.mockReset(); mocks.composition.mockReturnValue({ owner: { id: "owner", username: "ngoc", displayName: "Ngoc", passwordScrypt: `salt:${scryptSync("password", "salt", 64).toString("hex")}`, sessionSecret: "test-secret" }, gateway: {}, readModel: {}, loginRateLimiter: { isLocked: vi.fn().mockResolvedValue(false), recordFailure: vi.fn().mockResolvedValue(false), reset: vi.fn().mockResolvedValue(undefined) } }); mocks.headers.mockResolvedValue(new Headers({ "x-forwarded-for": "203.0.113.7" })); mocks.cookieGet.mockReturnValue({ value: "session" }); });
  it("rejects invalid UUID, timestamp, and missing version before composition", async () => { await expect(confirmOwnerDispatch(initial, form({ orderId: "mock-id" }))).resolves.toMatchObject({ ok: false }); await expect(confirmOwnerDispatch(initial, form({ startsAt: "bad" }))).resolves.toMatchObject({ ok: false }); await expect(confirmOwnerDispatch(initial, form({ expectedOrderVersion: "" }))).resolves.toMatchObject({ ok: false }); expect(mocks.composition).not.toHaveBeenCalled(); });
  it("passes only normalized confirm input and revalidates only on success", async () => { const data = form({ ownerId: "attacker", role: "OWNER", eligible: "true", score: "999", isOverride: "true" }); mocks.confirm.mockResolvedValue({ ok: true, result: {} }); await expect(confirmOwnerDispatch(initial, data)).resolves.toEqual({ ok: true, message: "Đã lưu điều phối." }); expect(mocks.confirm).toHaveBeenCalledWith(expect.objectContaining({ orderId: data.get("orderId"), employeeId: data.get("employeeId") }), "session", expect.anything()); expect(mocks.confirm.mock.calls[0][0]).not.toHaveProperty("ownerId"); expect(mocks.confirm.mock.calls[0][0]).not.toHaveProperty("isOverride"); expect(mocks.revalidate).toHaveBeenCalledWith("/owner"); });
  it("returns safe confirm failures without revalidation or override fallback", async () => { mocks.confirm.mockResolvedValue({ ok: false, error: "STALE_VERSION", message: "Dữ liệu tour đã thay đổi. Hãy tải lại trước khi xác nhận." }); await expect(confirmOwnerDispatch(initial, form())).resolves.toEqual({ ok: false, message: "Dữ liệu tour đã thay đổi. Hãy tải lại trước khi xác nhận." }); expect(mocks.revalidate).not.toHaveBeenCalled(); expect(mocks.override).not.toHaveBeenCalled(); });
  it("requires and trims an explicit override reason before using the separate command", async () => { await expect(overrideOwnerDispatch(initial, form({ overrideReason: "   " }))).resolves.toMatchObject({ ok: false }); expect(mocks.composition).not.toHaveBeenCalled(); mocks.override.mockResolvedValue({ ok: true, result: {} }); await overrideOwnerDispatch(initial, form({ overrideReason: "  Owner reason  ", isOverride: "false" })); expect(mocks.override).toHaveBeenCalledWith(expect.objectContaining({ reason: "Owner reason" }), "session", expect.anything()); expect(mocks.confirm).not.toHaveBeenCalled(); expect(mocks.revalidate).toHaveBeenCalledWith("/owner"); });
  it("does not leak persistence details from command failures", async () => { mocks.override.mockResolvedValue({ ok: false, error: "PERSISTENCE_FAILURE", message: "Không thể lưu điều phối. Vui lòng thử lại." }); const result = await overrideOwnerDispatch(initial, form({ overrideReason: "Reason", rawSql: "password" })); expect(result).toEqual({ ok: false, message: "Không thể lưu điều phối. Vui lòng thử lại." }); expect(JSON.stringify(result)).not.toContain("password"); expect(mocks.revalidate).not.toHaveBeenCalled(); });
  it("submits only employee/date OFF intent and revalidates only after success", async () => { const data = new FormData(); data.set("employeeId", "00000000-0000-4000-8000-000000000002"); data.set("offDate", "2030-01-01"); data.set("ownerId", "attacker"); mocks.markOff.mockResolvedValue({ ok: true }); await expect(markOwnerEmployeeOff(initial, data)).resolves.toMatchObject({ ok: true }); expect(mocks.markOff).toHaveBeenCalledWith({ employeeId: data.get("employeeId"), offDate: "2030-01-01" }, "session", expect.anything()); expect(mocks.revalidate).toHaveBeenCalledWith("/owner"); vi.clearAllMocks(); mocks.unmarkOff.mockResolvedValue({ ok: false, error: "EMPLOYEE_NOT_FOUND", message: "Không tìm thấy nhân viên." }); await expect(unmarkOwnerEmployeeOff(initial, data)).resolves.toMatchObject({ ok: false }); expect(mocks.revalidate).not.toHaveBeenCalled(); });
  it("logs in with a signed HttpOnly owner cookie and redirects only to /owner", async () => { const data = new FormData(); data.set("username", "ngoc"); data.set("password", "password"); await login(data); expect(mocks.cookieSet).toHaveBeenCalledWith("dispatch_session", expect.stringContaining("."), expect.objectContaining({ httpOnly: true, sameSite: "lax", path: "/", maxAge: 28800 })); expect(mocks.redirect).toHaveBeenCalledWith("/owner"); });
  it("uses a generic invalid-login redirect and clears logout sessions", async () => { mocks.redirect.mockImplementationOnce(() => { throw new Error("REDIRECT"); }); const invalid = new FormData(); invalid.set("username", "ngoc"); invalid.set("password", "wrong"); await expect(login(invalid)).rejects.toThrow("REDIRECT"); expect(mocks.redirect).toHaveBeenCalledWith("/login?error=invalid"); mocks.redirect.mockReset(); await logout(); expect(mocks.cookieSet).toHaveBeenCalledWith("dispatch_session", "", expect.objectContaining({ httpOnly: true, sameSite: "lax", path: "/", maxAge: 0 })); expect(mocks.redirect).toHaveBeenCalledWith("/login"); });
  it("records generic invalid logins by forwarded IP and resets that IP after success", async () => { const limiter = mocks.composition().loginRateLimiter; mocks.redirect.mockImplementationOnce(() => { throw new Error("REDIRECT"); }); await expect(login(form({ username: "ngoc", password: "wrong" }))).rejects.toThrow("REDIRECT"); expect(limiter.recordFailure).toHaveBeenCalledWith("203.0.113.7"); expect(limiter.reset).not.toHaveBeenCalled(); mocks.redirect.mockReset(); await login(form({ username: "ngoc", password: "password" })); expect(limiter.reset).toHaveBeenCalledWith("203.0.113.7"); });
  it("rejects a locked IP with the same generic response before password verification", async () => { const limiter = mocks.composition().loginRateLimiter; limiter.isLocked.mockResolvedValue(true); mocks.redirect.mockImplementationOnce(() => { throw new Error("REDIRECT"); }); await expect(login(form({ username: "ngoc", password: "password" }))).rejects.toThrow("REDIRECT"); expect(mocks.redirect).toHaveBeenCalledWith("/login?error=invalid"); expect(limiter.recordFailure).not.toHaveBeenCalled(); expect(limiter.reset).not.toHaveBeenCalled(); });
});
