/** @vitest-environment jsdom */
import { cleanup, render, screen } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ authenticate: vi.fn(), redirect: vi.fn(), list: vi.fn(), branches: vi.fn(), dailyOff: vi.fn(), recommendations: vi.fn() }));
vi.mock("next/headers", () => ({ cookies: vi.fn(async () => ({ get: () => ({ value: "session" }) })) }));
vi.mock("next/navigation", () => ({ redirect: mocks.redirect }));
vi.mock("@/server/owner-auth", () => ({ authenticateSession: mocks.authenticate }));
vi.mock("@/server/dispatch-composition", () => ({ createDispatchServerDependencies: () => ({ owner: {}, readModel: { listOwnerDispatchTours: mocks.list, listOwnerDispatchBranches: mocks.branches, listDailyOffEmployees: mocks.dailyOff, listCandidateRecommendationsForTours: mocks.recommendations } }) }));
vi.mock("@/app/owner/OwnerDailyOffPanel", () => ({ OwnerDailyOffPanel: (props: { offCount: number; maxOff: number }) => <div data-testid="daily-off">{props.offCount}/{props.maxOff}</div> }));
vi.mock("@/features/dispatch/OwnerDispatchDashboard", () => ({ OwnerDispatchDashboard: (props: { tours: typeof tour[]; recommendations: Array<Array<{ employeeName: string }>>; mapModel: { warnings: string[] } }) => props.tours.length === 0 ? <p>Chưa có tour cần điều phối.</p> : <div>{props.tours.map((item, index) => <div key={item.id}>{item.customerName} {item.location.name} Dịch vụ: {item.services.map((service) => service.name).join(", ")} {item.assignments.map((assignment) => `${assignment.employeeName} (${assignment.status})${assignment.isOverride ? ` | Ghi đè: ${assignment.overrideReason}` : ""}`).join(", ")} {item.orderVersion}:{props.recommendations[index].map((candidate) => candidate.employeeName).join(",")}</div>)}</div> }));
import OwnerDispatchPage from "@/app/owner/page";

const tour = { id: "00000000-0000-4000-8000-000000000001", customerName: "Durable Customer", customerPhone: null, requestedAt: "2030-01-01T08:00:00Z", orderType: "NEW_TOUR", urgency: "PREBOOKED", status: "ASSIGNED", notes: "", location: { id: "location", name: "Durable Location", address: "Address", latitude: 10, longitude: 106 }, services: [{ id: "service", name: "Durable Service", durationMinutes: 60 }], assignments: [{ id: "a1", employeeId: "e1", employeeName: "Employee One", startsAt: "start", endsAt: "end", status: "SCHEDULED", isOverride: false, overrideReason: null }, { id: "a2", employeeId: "e2", employeeName: "Employee Two", startsAt: "start", endsAt: "end", status: "DELAYED", isOverride: true, overrideReason: "Owner reason" }], orderVersion: "exact-version" };
describe("owner page boundary", () => {
  beforeEach(() => { vi.clearAllMocks(); mocks.authenticate.mockReset(); mocks.redirect.mockReset(); mocks.list.mockResolvedValue([]); mocks.branches.mockResolvedValue([]); mocks.dailyOff.mockResolvedValue({ employees: [], offCount: 0, maxOff: 2 }); mocks.recommendations.mockResolvedValue([]); });
  afterEach(cleanup);
  it("redirects when server-side owner authentication fails", async () => { mocks.authenticate.mockImplementation(() => { throw new Error("UNAUTHENTICATED"); }); mocks.redirect.mockImplementation(() => { throw new Error("REDIRECT"); }); await expect(OwnerDispatchPage()).rejects.toThrow("REDIRECT"); expect(mocks.redirect).toHaveBeenCalledWith("/login"); expect(mocks.list).not.toHaveBeenCalled(); });
  it("renders a durable empty state without mock fallback", async () => { render(await OwnerDispatchPage()); expect(screen.getByText("Chưa có tour cần điều phối.")).toBeTruthy(); expect(screen.queryByText("Khách demo")).toBeNull(); });
  it("renders durable tour projection, assignments, override data, recommendations, and version", async () => { mocks.list.mockResolvedValue([tour]); mocks.recommendations.mockResolvedValue([{ orderId: tour.id, recommendations: [{ employeeName: "Candidate" }] }]); render(await OwnerDispatchPage()); for (const text of ["Durable Customer", "Durable Location", "Dịch vụ: Durable Service", "Employee One (SCHEDULED), Employee Two (DELAYED) | Ghi đè: Owner reason", "exact-version:Candidate"]) expect(screen.getByText(text, { exact: false })).toBeTruthy(); });
  it("renders a safe read error instead of a false empty state", async () => { mocks.list.mockRejectedValue(new Error("password raw SQL")); render(await OwnerDispatchPage()); expect(screen.getByRole("alert").textContent).toContain("Không thể tải dữ liệu"); expect(document.body.textContent).not.toContain("password raw SQL"); expect(screen.queryByText("Chưa có tour cần điều phối.")).toBeNull(); });
});
